
language: python

python:
    - 3.6

install:
    -pip install -r requirements.txt

before_install:
    - pip install pytest pytest-cov
    - pip install coveralls

script:
    -  pytest --cov=src --cov-report term-missing

after_success:
    - coveralls