language: python

python:
    - 3.6
services:
  - postgresql

install:
    - pip install -r requirements.txt



script:
    - psql -c 'create database fast-food-fast-test;' -U postgres
    - python -m pytest --cov=app --cov-report term-missing


after_success:
    - coveralls